### PR TITLE
Ticket6

### PR DESCRIPTION
**Pull request by RossLockhart**
next step will be to accommodate for being provided with an endpoint that doesn't exist

### CODE REVIEW

**Review by hevdevs — CHANGES_REQUESTED** [review]
Looking great Ross! 🔥💯 couple of bits that aren't shown in this pull request need to be fixed: 
- We're getting an error because you need to give each ReviewCard a unique key identifier. On line 19 of AllReviews where you are mapping through your reviews and rendering a ReviewCard for each item, giving that ReviewCard component the unique key instead of the li in your ReviewCard so that react can differentiate between each item in the array it's mapping through should fix this
 i.e. <ReviewCard key={review.review_id} review={review}> 
- Remove the console log in ReviewCard before merge
Submit another PR once this error is fixed!

**Comment by pkaodev** [comment]
Looking good, but we have to do a bit of error handling.

If I go to /reviews/fewfwef or /reviews/9999 I am seeing a 'broken' review page.  What we would like to see is a message along the lines of "404 review not found" or something like that.

What do we get back from the api when we send a request for one of these?  how could we use that to render this 404 page?

**Comment by pkaodev** [comment]
Please put in another PR after that is done

**Review by hevdevs — APPROVED** [review]
Looks good to merge 👍 As we discussed, we can give more descriptive error messages by passing down the err response object to our error page component, which you may want to implement later!

**Pull request merged**
